# Generated by Django 5.0.6 on 2024-06-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analyser", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagedata",
            old_name="image_id",
            new_name="id",
        ),
        migrations.AddField(
            model_name="imagedata",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imagedata",
            name="format",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="imagedata",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
